import type { JsonSchema } from '@excitedjs/dreamux-types';

const NULLABLE_STRING: JsonSchema = { type: ['string', 'null'] };

/** The one closed Team projection advertised by create, list, and status. */
export const TEAM_SUMMARY_SCHEMA: JsonSchema & Record<string, unknown> = {
  type: 'object',
  additionalProperties: false,
  properties: {
    team_name: { type: 'string' },
    status: { type: 'string', enum: ['starting', 'running', 'closed'] },
    intent: NULLABLE_STRING,
    created_at: { type: 'integer' },
    updated_at: { type: 'integer' },
    closed_at: { type: ['integer', 'null'] },
    close_note: NULLABLE_STRING,
    leader_name: { type: 'string' },
    leader_agent_runtime: { type: 'string' },
    runtime_cwd: { type: 'string' },
    leader_state: {
      type: ['string', 'null'],
      enum: ['starting', 'running', 'degraded', 'stopped', 'closed', null],
    },
    leader_session_id: NULLABLE_STRING,
    leader_runtime_status: {
      type: ['string', 'null'],
      enum: [
        'declared',
        'starting',
        'ready',
        'degraded',
        'stopping',
        'stopped',
        null,
      ],
    },
    leader_intent: NULLABLE_STRING,
    leader_last_error: NULLABLE_STRING,
    leader_closed_at: { type: ['integer', 'null'] },
    leader_close_note: NULLABLE_STRING,
    member_count: { type: 'integer' },
    source_repo: NULLABLE_STRING,
    worktree_mode: { type: 'string', enum: ['reuse-cwd', 'managed'] },
    worktree_cleanup_mode: {
      type: 'string',
      enum: ['keep', 'delete-on-close'],
    },
    worktree_cleanup: {
      type: 'string',
      enum: [
        'not-managed',
        'managed-active',
        'cleanup-pending',
        'kept',
        'deleted',
        'retained-dirty',
        'retained-unmerged',
        'retained-unique-commits',
        'retained-error',
      ],
    },
  },
  required: [
    'team_name',
    'status',
    'intent',
    'created_at',
    'updated_at',
    'closed_at',
    'close_note',
    'leader_name',
    'leader_agent_runtime',
    'runtime_cwd',
    'leader_state',
    'leader_session_id',
    'leader_runtime_status',
    'leader_intent',
    'leader_last_error',
    'leader_closed_at',
    'leader_close_note',
    'member_count',
    'source_repo',
    'worktree_mode',
    'worktree_cleanup_mode',
    'worktree_cleanup',
  ],
};
