import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import {
  DISPATCHER_APP_SERVER_SOCKET_PATH_MAX_BYTES,
  formatDispatcherCodexHomeErrors,
  dispatcherCodexHomeDoctorContext,
  validateDispatcherCodexHome,
} from '../src/runtime/dispatcher-codex-home.js';
import { BUILT_IN_DEFAULTS } from '../src/runtime/config.js';
import {
  dispatcherAppServerControlDir,
  dispatcherCodexConfigPath,
  dispatcherCodexHome,
  dispatcherCodexPluginsDir,
  dispatcherSocketPath,
  resetRuntimeConfig,
  setRuntimeConfig,
} from '../src/runtime/paths.js';

const VALID_CONFIG = `model = "gpt-test"
approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[marketplaces.dreamux]
source = "public"

	[plugins.codexmux]
	enabled = true
	`;

const MODEL_ONLY_CONFIG = `model = "gpt-test"
approval_policy = "never"

[marketplaces.dreamux]
source = "public"

[plugins.codexmux]
enabled = true
`;

describe('dispatcher private CODEX_HOME doctor', () => {
  let runtimeDir: string;

  beforeEach(() => {
    runtimeDir = mkdtempSync(join(homedir(), '.dreamux-test-'));
    setRuntimeConfig({ ...BUILT_IN_DEFAULTS, runtime_dir: runtimeDir });
  });

  afterEach(() => {
    resetRuntimeConfig();
    rmSync(runtimeDir, { recursive: true, force: true });
  });

  it('places app-server sockets under the dispatcher private CODEX_HOME', () => {
    expect(dispatcherSocketPath('flow')).toBe(
      join(dispatcherAppServerControlDir('flow'), 'as.sock'),
    );
    expect(dispatcherSocketPath('flow')).toContain(
      join('dispatchers', 'flow', 'codex-home', 'app-server-control'),
    );
    expect(dispatcherSocketPath('flow')).not.toMatch(/^\/tmp(?:\/|$)/);
    expect(Buffer.byteLength(dispatcherSocketPath('frontend-service'), 'utf8'))
      .toBeLessThanOrEqual(DISPATCHER_APP_SERVER_SOCKET_PATH_MAX_BYTES);
  });

  it('reports every missing dispatcher home requirement', () => {
    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(false);
    expect(result.errors).toEqual(
      expect.arrayContaining([
        expect.stringContaining('missing dispatcher Codex config'),
        expect.stringContaining('missing dispatcher CODEX_HOME directory'),
        expect.stringContaining('missing codexmux plugin'),
        expect.stringContaining('missing dispatcher Codex auth state'),
      ]),
    );
  });

  it('accepts a minimal dispatcher home generated by onboard', () => {
    writeDispatcherHome('flow', VALID_CONFIG);

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
  });

  it('rejects restricted-network dispatcher configs', () => {
    writeDispatcherHome(
      'flow',
      `model = "gpt-test"
approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = false
`,
    );

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      'network-enabled sandbox/profile',
    );
  });

  it('accepts runtime CLI sandbox overrides as effective network state', () => {
    writeDispatcherHome('flow', MODEL_ONLY_CONFIG);

    const result = validateDispatcherCodexHome('flow', {
      codexCliArgs: ['-c', 'sandbox_mode=danger-full-access'],
      env: {},
    });

    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
  });

  it('rejects config network when runtime CLI overrides turn it off', () => {
    writeDispatcherHome('flow', VALID_CONFIG);

    const result = validateDispatcherCodexHome('flow', {
      codexCliArgs: [
        '-c',
        'sandbox_mode=workspace-write',
        '-c',
        'sandbox_workspace_write.network_access=false',
      ],
      env: {},
    });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      'network-enabled sandbox/profile',
    );
  });

  it('accepts Codex 0.135 default_permissions network profile config', () => {
    writeDispatcherHome(
      'flow',
      `model = "gpt-test"
approval_policy = "never"
default_permissions = "dispatcher"

[permissions.dispatcher]
network = { enabled = true }
`,
    );

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(true);
  });

  it('rejects too-long app-server socket paths before bind', () => {
    setRuntimeConfig({
      ...BUILT_IN_DEFAULTS,
      runtime_dir: join(runtimeDir, 'runtime-root-with-a-long-custom-name'),
    });
    writeDispatcherHome('dispatcher-with-long-id', VALID_CONFIG);

    const result = validateDispatcherCodexHome('dispatcher-with-long-id', {
      env: {},
    });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      'socket path is too long',
    );
  });

  it('requires auth environment variables to be non-empty and accepts CODEX_ACCESS_TOKEN', () => {
    writeDispatcherHome('flow', VALID_CONFIG, { writeAuth: false });

    const emptyAuth = validateDispatcherCodexHome('flow', {
      env: { OPENAI_API_KEY: '' },
    });
    expect(emptyAuth.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(emptyAuth)).toContain(
      'missing dispatcher Codex auth state',
    );

    const accessToken = validateDispatcherCodexHome('flow', {
      env: { CODEX_ACCESS_TOKEN: 'token-test' },
    });
    expect(accessToken.ok).toBe(true);
  });

  it('honors caller-provided doctor context paths', () => {
    writeDispatcherHome('flow', VALID_CONFIG);
    const context = dispatcherCodexHomeDoctorContext('flow', {
      codexCliArgs: ['-c', 'sandbox_mode=danger-full-access'],
    });

    const result = validateDispatcherCodexHome({
      ...context,
      configPath: join(runtimeDir, 'missing-config.toml'),
    }, { env: {} });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      join(runtimeDir, 'missing-config.toml'),
    );
  });

  it('rejects dispatcher homes without codexmux installed', () => {
    writeDispatcherHome('flow', VALID_CONFIG, { installCodexmux: false });

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      'missing codexmux plugin',
    );
  });
});

function writeDispatcherHome(
  dispatcherId: string,
  config: string,
  options: { installCodexmux?: boolean; writeAuth?: boolean } = {},
): void {
  mkdirSync(dispatcherCodexHome(dispatcherId), { recursive: true });
  writeFileSync(dispatcherCodexConfigPath(dispatcherId), config, { mode: 0o600 });
  if (options.writeAuth !== false) {
    writeFileSync(join(dispatcherCodexHome(dispatcherId), 'auth.json'), '{}', {
      mode: 0o600,
    });
  }

  if (options.installCodexmux === false) return;
  mkdirSync(
    join(
      dispatcherCodexPluginsDir(dispatcherId),
      'cache',
      'dreamux',
      'codexmux',
    ),
    { recursive: true },
  );
}
