import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import {
  formatDispatcherCodexHomeErrors,
  validateDispatcherCodexHome,
} from '../src/runtime/dispatcher-codex-home.js';
import { BUILT_IN_DEFAULTS } from '../src/runtime/config.js';
import {
  dispatcherAppServerControlDir,
  dispatcherCodexConfigPath,
  dispatcherCodexHome,
  dispatcherCodexPluginsDir,
  dispatcherSocketPath,
  resetRuntimeConfig,
  setRuntimeConfig,
} from '../src/runtime/paths.js';

const VALID_CONFIG = `model = "gpt-test"
approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[marketplaces.dreamux]
source = "public"

[plugins.codexmux]
enabled = true
`;

describe('dispatcher private CODEX_HOME doctor', () => {
  let runtimeDir: string;

  beforeEach(() => {
    runtimeDir = mkdtempSync(join(homedir(), '.dreamux-test-'));
    setRuntimeConfig({ ...BUILT_IN_DEFAULTS, runtime_dir: runtimeDir });
  });

  afterEach(() => {
    resetRuntimeConfig();
    rmSync(runtimeDir, { recursive: true, force: true });
  });

  it('places app-server sockets under the dispatcher private CODEX_HOME', () => {
    expect(dispatcherSocketPath('flow')).toBe(
      join(
        dispatcherAppServerControlDir('flow'),
        'app-server-control.sock',
      ),
    );
    expect(dispatcherSocketPath('flow')).toContain(
      join('dispatchers', 'flow', 'codex-home', 'app-server-control'),
    );
    expect(dispatcherSocketPath('flow')).not.toMatch(/^\/tmp(?:\/|$)/);
  });

  it('reports every missing dispatcher home requirement', () => {
    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(false);
    expect(result.errors).toEqual(
      expect.arrayContaining([
        expect.stringContaining('missing dispatcher Codex config'),
        expect.stringContaining('missing dispatcher CODEX_HOME directory'),
        expect.stringContaining('missing dispatcher app-server control directory'),
        expect.stringContaining('missing codexmux plugin'),
        expect.stringContaining('missing dispatcher Codex auth state'),
      ]),
    );
  });

  it('accepts a minimal dispatcher home generated by onboard', () => {
    writeDispatcherHome('flow', VALID_CONFIG);

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
  });

  it('rejects restricted-network dispatcher configs', () => {
    writeDispatcherHome(
      'flow',
      `model = "gpt-test"
approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = false
`,
    );

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      'network-enabled sandbox/profile',
    );
  });

  it('rejects dispatcher homes without codexmux installed', () => {
    writeDispatcherHome('flow', VALID_CONFIG, { installCodexmux: false });

    const result = validateDispatcherCodexHome('flow', { env: {} });

    expect(result.ok).toBe(false);
    expect(formatDispatcherCodexHomeErrors(result)).toContain(
      'missing codexmux plugin',
    );
  });
});

function writeDispatcherHome(
  dispatcherId: string,
  config: string,
  options: { installCodexmux?: boolean } = {},
): void {
  mkdirSync(dispatcherAppServerControlDir(dispatcherId), { recursive: true });
  mkdirSync(dispatcherCodexHome(dispatcherId), { recursive: true });
  writeFileSync(dispatcherCodexConfigPath(dispatcherId), config, { mode: 0o600 });
  writeFileSync(join(dispatcherCodexHome(dispatcherId), 'auth.json'), '{}', {
    mode: 0o600,
  });

  if (options.installCodexmux === false) return;
  mkdirSync(
    join(
      dispatcherCodexPluginsDir(dispatcherId),
      'cache',
      'dreamux',
      'codexmux',
    ),
    { recursive: true },
  );
}
