/**
 * Feishu access gate v3 — the pure decision function.
 *
 * `dreamuxFeishuGate` decides `deliver | drop | pair` against a snapshot of
 * `DispatcherAccessStateV3` (`./state.js`) and returns the next state plus
 * logs. It touches no disk and sends nothing; the session owns IO, the access
 * store's serialized queue, and send-before-save for pairing prompts (see
 * `./index.js`'s `FeishuAccess`).
 */

import { randomBytes } from 'node:crypto';

import {
  MAX_PENDING,
  PAIRING_TOKEN_BYTES,
  PAIRING_TTL_MS,
  type DispatcherAccessStateV3,
  type PendingPairingEntry,
  type PendingPairingKind,
} from './state.js';

// ─────────────────────────────────────────────────────────────────────────
// Pairing token generators — the token-minting half of the `pair` transition
// ─────────────────────────────────────────────────────────────────────────

export function generatePairingToken(): string {
  return randomBytes(PAIRING_TOKEN_BYTES).toString('hex');
}

export function generateUniquePairingToken(
  existing: Record<string, unknown>,
): string {
  let token = generatePairingToken();
  let guard = 0;
  while (existing[token] !== undefined && guard++ < 1000) {
    token = generatePairingToken();
  }
  return token;
}

export interface GateInbound {
  chat_type: 'p2p' | 'group';
  sender_id: string;
  chat_id: string;
  /**
   * The session must classify the sender exactly before calling the gate:
   * `false` means sender_type=user with a non-empty sender id, not merely
   * "isBotSenderType returned false" for an unknown sender type.
   */
  is_bot_sender: boolean;
  trusted_bot: boolean;
  bot_mentioned: boolean;
}

export type DropReason =
  | 'dm_disabled'
  | 'dm_not_on_allowlist'
  | 'dm_pairing_slot_cap'
  | 'group_policy_block'
  | 'group_bot_not_mentioned'
  // Legacy drop reasons retained on the exported type for read-compat with
  // source/tests written before the C3 semantic rewrite. Not generated by new
  // paths. Current group handling either uses trusted-chat delivery or emits
  // the current policy, sender, or DM-path reasons instead.
  | 'group_not_on_allowlist_and_not_mentioned'
  | 'group_follow_user_stranger_not_mentioned'
  | 'group_pairing_slot_cap'
  // New drop reasons after the C3 rewrite:
  | 'group_not_on_allowlist' // rule 1: group not on allowlist at all
  | 'group_user_not_on_allowlist' // rule 2: user not on allowlist (dm=allowlist)
  | 'group_pairing_stranger_not_mentioned' // rule 3: stranger in group, dm=pairing, not @
  | 'bot_untrusted'
  | 'unsupported_chat_type'
  | 'internal';

export type GateAction =
  | { action: 'deliver' }
  | {
      action: 'drop';
      reason: DropReason;
      context?: Record<string, unknown>;
    }
  | {
      action: 'pair';
      kind: PendingPairingKind;
      token: string;
      is_resend: boolean;
      ttl_left_ms: number;
      prompt_message_id?: string;
    };

export interface GateResult {
  action: GateAction;
  nextState: DispatcherAccessStateV3;
  logs: Array<{
    level: 'debug' | 'info' | 'warn' | 'error';
    msg: string;
    ctx?: Record<string, unknown>;
  }>;
}

// ─────────────────────────────────────────────────────────────────────────
// Pure helpers
// ─────────────────────────────────────────────────────────────────────────

type PendingMap = Record<string, PendingPairingEntry>;

export function pruneExpiredPending(
  state: DispatcherAccessStateV3,
  now: number,
): DispatcherAccessStateV3 {
  const kept: PendingMap = {};
  let anyRemoved = false;
  for (const [token, entry] of Object.entries(state.pending)) {
    if (entry.expires_at > now) {
      kept[token] = entry;
    } else {
      anyRemoved = true;
    }
  }
  return anyRemoved ? { ...state, pending: kept } : state;
}

interface FoundPending {
  token: string;
  entry: PendingPairingEntry;
}

// Every live pending entry is dm-kind (the C3 semantic rewrite removed group
// pairing below), so an existing slot is found by sender alone.
function findExistingPendingByKey(
  pending: PendingMap,
  sender_id: string,
  now: number,
): FoundPending | null {
  for (const [token, entry] of Object.entries(pending)) {
    if (entry.expires_at <= now) continue;
    if (entry.sender_id === sender_id) {
      return { token, entry };
    }
  }
  return null;
}

function countActivePending(pending: PendingMap, now: number): number {
  let count = 0;
  for (const entry of Object.values(pending)) {
    if (entry.expires_at <= now) continue;
    count += 1;
  }
  return count;
}

// ─────────────────────────────────────────────────────────────────────────
// Pairing subpath (dm-kind only — C3 semantic rewrite removed group pairing)
// ─────────────────────────────────────────────────────────────────────────

interface FinalizeOpts {
  state: DispatcherAccessStateV3;
  input: GateInbound;
  now: number;
  logs: GateResult['logs'];
}

// NOTE: groupPairPath was removed as part of the C3 semantic rewrite.
// group.allow_chats is operator-maintained; there is no pairing mechanism to
// add a chat to it. All untrusted-chat pairing triggers route through
// dmPairPath and end up as dm-kind entries on allow_users.

function dmPairPath(opts: FinalizeOpts): GateResult {
  const { state, input, now, logs } = opts;
  const existing = findExistingPendingByKey(
    state.pending,
    input.sender_id,
    now,
  );

  if (existing !== null) {
    const { token, entry } = existing;
    const newEntry: PendingPairingEntry = {
      ...entry,
      expires_at: now + PAIRING_TTL_MS,
    };
    const nextState: DispatcherAccessStateV3 = {
      ...state,
      pending: { ...state.pending, [token]: newEntry },
    };
    logs.push({
      level: 'info',
      msg: 'dm pairing: existing prompt',
      ctx: {
        pairing_token_len: token.length,
        sender_id: input.sender_id,
        chat_id: input.chat_id,
        prompt_message_id: entry.prompt_message_id,
      },
    });
    return {
      action: {
        action: 'pair',
        kind: 'dm',
        token,
        is_resend: true,
        ttl_left_ms: PAIRING_TTL_MS,
        ...(entry.prompt_message_id !== undefined
          ? { prompt_message_id: entry.prompt_message_id }
          : {}),
      },
      nextState,
      logs,
    };
  }

  const count = countActivePending(state.pending, now);
  if (count >= MAX_PENDING) {
    logs.push({
      level: 'warn',
      msg: 'dm pairing: slot cap reached',
      ctx: { count, sender_id: input.sender_id, chat_id: input.chat_id },
    });
    return {
      action: {
        action: 'drop',
        reason: 'dm_pairing_slot_cap',
        context: { pending: count, max: MAX_PENDING },
      },
      nextState: state,
      logs,
    };
  }

  const token = generateUniquePairingToken(state.pending);
  const entry: PendingPairingEntry = {
    sender_id: input.sender_id,
    chat_id: input.chat_id,
    created_at: now,
    expires_at: now + PAIRING_TTL_MS,
  };
  const nextState: DispatcherAccessStateV3 = {
    ...state,
    pending: { ...state.pending, [token]: entry },
  };
  logs.push({
    level: 'info',
    msg: 'dm pairing: new slot',
    ctx: {
      pairing_token_len: token.length,
      sender_id: input.sender_id,
      chat_id: input.chat_id,
    },
  });
  return {
    action: {
      action: 'pair',
      kind: 'dm',
      token,
      is_resend: false,
      ttl_left_ms: PAIRING_TTL_MS,
    },
    nextState,
    logs,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Core gate
// ─────────────────────────────────────────────────────────────────────────

export function dreamuxFeishuGate(
  state: DispatcherAccessStateV3,
  input: GateInbound,
  now: number = Date.now(),
): GateResult {
  const logs: GateResult['logs'] = [];

  // Double-guard TTL — prune first, then helpers also check expires_at > now.
  let working: DispatcherAccessStateV3 = pruneExpiredPending(state, now);

  const finish = (
    action: GateAction,
    mutate: (s: DispatcherAccessStateV3) => DispatcherAccessStateV3 = (s) => s,
  ): GateResult => {
    return { action, nextState: mutate(working), logs };
  };

  // ── DM ────────────────────────────────────────────────────────────────
  if (input.chat_type === 'p2p') {
    if (input.is_bot_sender) {
      return finish({
        action: 'drop',
        reason: 'bot_untrusted',
        context: { sender_id: input.sender_id },
      });
    }
    switch (working.dm_policy) {
      case 'disabled':
        return finish({ action: 'drop', reason: 'dm_disabled' });
      case 'all':
        return finish({ action: 'deliver' });
      case 'allowlist':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        return finish({
          action: 'drop',
          reason: 'dm_not_on_allowlist',
          context: { sender_id: input.sender_id },
        });
      case 'pairing':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        return dmPairPath({ state: working, input, now, logs });
      default:
        return finish({ action: 'drop', reason: 'internal' });
    }
  }

  // ── GROUP ─────────────────────────────────────────────────────────────
  if (input.chat_type === 'group') {
    // Bot senders first
    if (input.is_bot_sender) {
      if (!input.trusted_bot) {
        return finish({
          action: 'drop',
          reason: 'bot_untrusted',
          context: { sender_id: input.sender_id },
        });
      }
      if (!input.bot_mentioned) {
        return finish({ action: 'drop', reason: 'group_bot_not_mentioned' });
      }
      return finish({ action: 'deliver' });
    }

    // Human sender — mention gate (applies before policy logic; still
    // short-circuits silently when the bot isn't addressed, regardless of
    // allowlist status.)
    if (working.group.require_mention && !input.bot_mentioned) {
      return finish({ action: 'drop', reason: 'group_bot_not_mentioned' });
    }

    const policy = working.group.policy;
    if (policy === 'block') {
      return finish({ action: 'drop', reason: 'group_policy_block' });
    }

    // The V3 loader intentionally remains shallow and accepts any string here.
    // Fail closed before consulting allow_chats so a malformed persisted policy
    // cannot acquire trusted-chat authority.
    if (policy !== 'allowlist' && policy !== 'follow-user') {
      return finish({ action: 'drop', reason: 'internal' });
    }

    // Resolve the operator's group-trust decision once. A trusted chat admits
    // every exactly-classified human after the global mention and block gates;
    // it deliberately bypasses dm_policy, allow_users, and pairing. /introduce
    // remains sender-scoped and performs its own allow_users check.
    const chatTrusted = working.group.allow_chats.includes(input.chat_id);

    if (policy === 'allowlist' && !chatTrusted) {
      return finish({
        action: 'drop',
        reason: 'group_not_on_allowlist',
        context: { chat_id: input.chat_id },
      });
    }

    if (chatTrusted) {
      return finish({ action: 'deliver' });
    }

    // Only an untrusted follow-user chat reaches the existing sender path.
    // Pairing is always dm-kind (adds the sender to allow_users), never
    // group-kind.

    switch (working.dm_policy) {
      case 'disabled':
        return finish({ action: 'drop', reason: 'dm_disabled' });
      case 'all':
        return finish({ action: 'deliver' });
      case 'allowlist':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        return finish({
          action: 'drop',
          reason: 'group_user_not_on_allowlist',
          context: { sender_id: input.sender_id, chat_id: input.chat_id },
        });
      case 'pairing':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        // Rule 3: in-group pairing needs a mention (same as follow-user
        // gate). This triggers a dm-kind pair (adds sender to allow_users)
        // rather than any group-kind pair.
        if (!input.bot_mentioned) {
          return finish({
            action: 'drop',
            reason: 'group_pairing_stranger_not_mentioned',
            context: { sender_id: input.sender_id, chat_id: input.chat_id },
          });
        }
        return dmPairPath({ state: working, input, now, logs });
      default:
        return finish({ action: 'drop', reason: 'internal' });
    }
  }

  // Unsupported
  return finish({ action: 'drop', reason: 'unsupported_chat_type' });
}
