/**
 * Feishu access gate v3 — pairing-token model.
 *
 * Pure gate (`dreamuxFeishuGate`) decides `deliver | drop | pair` against a
 * snapshot of `DispatcherAccessStateV3` and returns the next state plus logs.
 * The session owns IO, mutex, and send-before-save for pairing prompts.
 *
 * v3 replaces the v2 "everything is allowlist" model with per-sender
 * pairing slots. An operator (human admin out-of-band) approves a 6-hex token
 * to add a sender to `allow_users`. `group.allow_chats` is a manual group
 * shell, not something pairing approval mutates.
 */

import { randomBytes } from 'node:crypto';

// ─────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────

export const ACCESS_STATE_VERSION = 3 as const;
// Ten active dm-kind onboarding slots keeps one dispatcher useful in a busy
// chat while bounding spam from many unknown senders.
export const MAX_PENDING_PER_KIND = 10;
export const PAIRING_TTL_MS = 60 * 60 * 1000;
export const PAIRING_TOKEN_BYTES = 3;
export const PAIRING_TOKEN_REGEX = /^[0-9a-fA-F]{6}$/;

const MAX_WARNINGS = 200;
/**
 * Flag emitted into `state.warnings` when a single dispatcher observes traffic
 * from more than one chat — the channel multiplexes chats over one runtime
 * context, which is supported but worth surfacing to an operator once.
 */
export const TRUST_DOMAIN_WARNING =
  'dispatcher shares one runtime context across multiple Feishu chats';

// ─────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────

export type DmPolicy = 'all' | 'allowlist' | 'pairing' | 'disabled';
export type GroupPolicy = 'block' | 'allowlist' | 'follow-user';
export type PendingPairingKind = 'dm' | 'group';

export interface PendingPairingEntry {
  kind: PendingPairingKind;
  sender_id: string;
  chat_id: string;
  created_at: number;
  expires_at: number;
  replies: number;
  prompt_message_id?: string;
}

export interface WarnEntry {
  at: number;
  msg: string;
  ctx?: Record<string, unknown>;
}

export interface LastGate {
  at: number;
  sender_id?: string;
  chat_id?: string;
  action?: string;
  reason?: string;
}

export interface DispatcherAccessStateV3 {
  version: typeof ACCESS_STATE_VERSION;
  dm_policy: DmPolicy;
  group: {
    policy: GroupPolicy;
    allow_chats: string[];
    require_mention: boolean;
  };
  allow_users: string[];
  pending: Record<string, PendingPairingEntry>;
  observed_chats: string[];
  warnings: WarnEntry[];
  last_gate: LastGate;
}

export type DispatcherAccessState = DispatcherAccessStateV3;

export interface GateInbound {
  chat_type: 'p2p' | 'group';
  sender_id: string;
  chat_id: string;
  is_bot_sender: boolean;
  trusted_bot: boolean;
  bot_mentioned: boolean;
}

export type DropReason =
  | 'dm_disabled'
  | 'dm_not_on_allowlist'
  | 'dm_pairing_slot_cap'
  | 'group_policy_block'
  | 'group_bot_not_mentioned'
  // Legacy drop reasons retained on the exported type for read-compat with
  // source/tests written before the C3 semantic rewrite. Not generated by new
  // paths. (Group pairing was removed; group allowlist drops everything, and
  // user-level checks in groups go through dm_policy.)
  | 'group_not_on_allowlist_and_not_mentioned'
  | 'group_follow_user_stranger_not_mentioned'
  | 'group_pairing_slot_cap'
  // New drop reasons after the C3 rewrite:
  | 'group_not_on_allowlist'           // rule 1: group not on allowlist at all
  | 'group_user_not_on_allowlist'      // rule 2: user not on allowlist (dm=allowlist)
  | 'group_pairing_stranger_not_mentioned' // rule 3: stranger in group, dm=pairing, not @
  | 'bot_untrusted'
  | 'unsupported_chat_type'
  | 'internal';

export type GateAction =
  | { action: 'deliver' }
  | {
      action: 'drop';
      reason: DropReason;
      context?: Record<string, unknown>;
    }
  | {
      action: 'pair';
      kind: PendingPairingKind;
      token: string;
      is_resend: boolean;
      ttl_left_ms: number;
      prompt_message_id?: string;
    };

export interface GateResult {
  action: GateAction;
  nextState: DispatcherAccessStateV3;
  logs: Array<{
    level: 'debug' | 'info' | 'warn' | 'error';
    msg: string;
    ctx?: Record<string, unknown>;
  }>;
}

// ─────────────────────────────────────────────────────────────────────────
// Defaults
// ─────────────────────────────────────────────────────────────────────────

export function defaultDispatcherAccessState(): DispatcherAccessStateV3 {
  return {
    version: ACCESS_STATE_VERSION,
    dm_policy: 'pairing',
    group: {
      policy: 'follow-user',
      allow_chats: [],
      require_mention: true,
    },
    allow_users: [],
    pending: {},
    observed_chats: [],
    warnings: [],
    last_gate: { at: 0 },
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Pairing token generators
// ─────────────────────────────────────────────────────────────────────────

export function generatePairingToken(): string {
  return randomBytes(PAIRING_TOKEN_BYTES).toString('hex');
}

export function generateUniquePairingToken(
  existing: Record<string, unknown>,
): string {
  let token = generatePairingToken();
  let guard = 0;
  while (existing[token] !== undefined && guard++ < 1000) {
    token = generatePairingToken();
  }
  return token;
}

// ─────────────────────────────────────────────────────────────────────────
// Pure helpers
// ─────────────────────────────────────────────────────────────────────────

type PendingMap = Record<string, PendingPairingEntry>;

function pruneExpiredPending(
  state: DispatcherAccessStateV3,
  now: number,
): DispatcherAccessStateV3 {
  const kept: PendingMap = {};
  let anyRemoved = false;
  for (const [token, entry] of Object.entries(state.pending)) {
    if (entry.expires_at > now) {
      kept[token] = entry;
    } else {
      anyRemoved = true;
    }
  }
  return anyRemoved ? { ...state, pending: kept } : state;
}

interface FoundPending {
  token: string;
  entry: PendingPairingEntry;
}

function findExistingPendingByKey(
  pending: PendingMap,
  kind: PendingPairingKind,
  sender_id: string,
  chat_id: string,
  now: number,
): FoundPending | null {
  for (const [token, entry] of Object.entries(pending)) {
    if (entry.expires_at <= now) continue;
    if (entry.kind !== kind) continue;
    if (kind === 'dm' && entry.sender_id === sender_id) {
      return { token, entry };
    }
    if (kind === 'group' && entry.chat_id === chat_id) {
      return { token, entry };
    }
  }
  return null;
}

interface KindCount {
  dm: number;
  group: number;
}

function countByKind(pending: PendingMap, now: number): KindCount {
  const c: KindCount = { dm: 0, group: 0 };
  for (const entry of Object.values(pending)) {
    if (entry.expires_at <= now) continue;
    c[entry.kind] += 1;
  }
  return c;
}

function pushWarn(
  warnings: WarnEntry[],
  at: number,
  msg: string,
  ctx?: Record<string, unknown>,
): WarnEntry[] {
  const next = [...warnings, { at, msg, ...(ctx ? { ctx } : {}) }];
  // cap at MAX_WARNINGS FIFO
  if (next.length > MAX_WARNINGS) {
    return next.slice(next.length - MAX_WARNINGS);
  }
  return next;
}

function pushObserved(
  observed: string[],
  chat_id: string,
): string[] {
  if (observed.includes(chat_id)) return observed;
  return [...observed, chat_id];
}

function withLastGate(
  state: DispatcherAccessStateV3,
  input: GateInbound,
  now: number,
  action: string,
  reason?: string,
): DispatcherAccessStateV3 {
  return {
    ...state,
    last_gate: {
      at: now,
      sender_id: input.sender_id,
      chat_id: input.chat_id,
      action,
      ...(reason !== undefined ? { reason } : {}),
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Pairing subpath (dm-kind only — C3 semantic rewrite removed group pairing)
// ─────────────────────────────────────────────────────────────────────────

interface FinalizeOpts {
  state: DispatcherAccessStateV3;
  input: GateInbound;
  now: number;
  logs: GateResult['logs'];
}

// NOTE: groupPairPath was removed as part of the C3 semantic rewrite (review
// comment of 2026-06-27 on PR #255). group.allow_chats is now a manual allowlist
// only; there is no pairing mechanism to add a chat to it. All in-group triggers
// route through dmPairPath and end up as dm-kind entries on allow_users.

function dmPairPath(opts: FinalizeOpts): GateResult {
  const { state, input, now, logs } = opts;
  const existing = findExistingPendingByKey(
    state.pending,
    'dm',
    input.sender_id,
    input.chat_id,
    now,
  );

  if (existing !== null) {
    const { token, entry } = existing;
    const newEntry: PendingPairingEntry = {
      ...entry,
      expires_at: now + PAIRING_TTL_MS,
    };
    let nextState: DispatcherAccessStateV3 = {
      ...state,
      pending: { ...state.pending, [token]: newEntry },
    };
    nextState = withLastGate(nextState, input, now, 'pair');
    nextState = { ...nextState, observed_chats: pushObserved(nextState.observed_chats, input.chat_id) };
    logs.push({
      level: 'info',
      msg: 'dm pairing: existing prompt',
      ctx: {
        token,
        sender_id: input.sender_id,
        ...(entry.prompt_message_id !== undefined
          ? { prompt_message_id: entry.prompt_message_id }
          : {}),
      },
    });
    return {
      action: {
        action: 'pair',
        kind: 'dm',
        token,
        is_resend: true,
        ttl_left_ms: PAIRING_TTL_MS,
        ...(entry.prompt_message_id !== undefined
          ? { prompt_message_id: entry.prompt_message_id }
          : {}),
      },
      nextState,
      logs,
    };
  }

  const counts = countByKind(state.pending, now);
  if (counts.dm >= MAX_PENDING_PER_KIND) {
    const msg = 'dm pairing: slot cap reached';
    const warnings = pushWarn(state.warnings, now, msg, {
      count: counts.dm,
      sender_id: input.sender_id,
    });
    logs.push({
      level: 'warn',
      msg,
      ctx: { count: counts.dm, sender_id: input.sender_id },
    });
    let nextState: DispatcherAccessStateV3 = { ...state, warnings };
    nextState = withLastGate(nextState, input, now, 'drop', 'dm_pairing_slot_cap');
    nextState = { ...nextState, observed_chats: pushObserved(nextState.observed_chats, input.chat_id) };
    return {
      action: {
        action: 'drop',
        reason: 'dm_pairing_slot_cap',
        context: { pending: counts.dm, max: MAX_PENDING_PER_KIND },
      },
      nextState,
      logs,
    };
  }

  const token = generateUniquePairingToken(state.pending);
  const entry: PendingPairingEntry = {
    kind: 'dm',
    sender_id: input.sender_id,
    chat_id: input.chat_id,
    created_at: now,
    expires_at: now + PAIRING_TTL_MS,
    replies: 1,
  };
  let nextState: DispatcherAccessStateV3 = {
    ...state,
    pending: { ...state.pending, [token]: entry },
  };
  nextState = withLastGate(nextState, input, now, 'pair');
  nextState = { ...nextState, observed_chats: pushObserved(nextState.observed_chats, input.chat_id) };
  logs.push({
    level: 'info',
    msg: 'dm pairing: new slot',
    ctx: { token, sender_id: input.sender_id },
  });
  return {
    action: {
      action: 'pair',
      kind: 'dm',
      token,
      is_resend: false,
      ttl_left_ms: PAIRING_TTL_MS,
    },
    nextState,
    logs,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Core gate
// ─────────────────────────────────────────────────────────────────────────

export function dreamuxFeishuGate(
  state: DispatcherAccessStateV3,
  input: GateInbound,
  now: number = Date.now(),
): GateResult {
  const logs: GateResult['logs'] = [];

  // Double-guard TTL — prune first, then helpers also check expires_at > now.
  let working: DispatcherAccessStateV3 = pruneExpiredPending(state, now);

  const finish = (
    action: GateAction,
    mutate: (s: DispatcherAccessStateV3) => DispatcherAccessStateV3 = (s) => s,
  ): GateResult => {
    let s = mutate(working);
    s = { ...s, observed_chats: pushObserved(s.observed_chats, input.chat_id) };
    // Attach trust-domain warning if we observe multiple chats.
    if (
      s.observed_chats.length > 1 &&
      !s.warnings.some((w) => w.msg === TRUST_DOMAIN_WARNING)
    ) {
      s = {
        ...s,
        warnings: pushWarn(s.warnings, now, TRUST_DOMAIN_WARNING),
      };
      logs.push({ level: 'warn', msg: TRUST_DOMAIN_WARNING });
    }
    const actionStr =
      action.action === 'drop'
        ? `drop:${action.reason}`
        : action.action === 'pair'
          ? `pair:${action.kind}`
          : 'deliver';
    const reason = action.action === 'drop' ? action.reason : undefined;
    s = withLastGate(s, input, now, actionStr, reason);
    return { action, nextState: s, logs };
  };

  // ── DM ────────────────────────────────────────────────────────────────
  if (input.chat_type === 'p2p') {
    if (input.is_bot_sender) {
      return finish({
        action: 'drop',
        reason: 'bot_untrusted',
        context: { sender_id: input.sender_id },
      });
    }
    switch (working.dm_policy) {
      case 'disabled':
        return finish({ action: 'drop', reason: 'dm_disabled' });
      case 'all':
        return finish({ action: 'deliver' });
      case 'allowlist':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        return finish({
          action: 'drop',
          reason: 'dm_not_on_allowlist',
          context: { sender_id: input.sender_id },
        });
      case 'pairing':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        return dmPairPath({ state: working, input, now, logs });
      default:
        return finish({ action: 'drop', reason: 'internal' });
    }
  }

  // ── GROUP ─────────────────────────────────────────────────────────────
  if (input.chat_type === 'group') {
    // Bot senders first
    if (input.is_bot_sender) {
      if (!input.trusted_bot) {
        return finish({
          action: 'drop',
          reason: 'bot_untrusted',
          context: { sender_id: input.sender_id },
        });
      }
      if (!input.bot_mentioned) {
        return finish({ action: 'drop', reason: 'group_bot_not_mentioned' });
      }
      return finish({ action: 'deliver' });
    }

    // Human sender — mention gate (applies before policy logic; still
    // short-circuits silently when the bot isn't addressed, regardless of
    // allowlist status.)
    if (working.group.require_mention && !input.bot_mentioned) {
      return finish({ action: 'drop', reason: 'group_bot_not_mentioned' });
    }

    const policy = working.group.policy;
    if (policy === 'block') {
      return finish({ action: 'drop', reason: 'group_policy_block' });
    }

    // Rule 1 (KB + review C3): group.allowlist + chat ∉ allow_chats →
    // DROP unconditionally. No pairing token can ever add a chat to the
    // group allowlist (pairing only manages allow_users). Even users who
    // are on allow_users get dropped here: the group allowlist is the
    // strict outer shell.
    if (
      policy === 'allowlist' &&
      !working.group.allow_chats.includes(input.chat_id)
    ) {
      return finish({
        action: 'drop',
        reason: 'group_not_on_allowlist',
        context: { chat_id: input.chat_id },
      });
    }

    // At this point the group shell is satisfied:
    //   - policy === 'follow_user' (no group allowlist), OR
    //   - policy === 'allowlist' AND chat_id ∈ allow_chats.
    //
    // Rule 2/3 (C3): the USER-LEVEL check is now the dm_policy switch,
    // identical for both group shells. Pairing is ALWAYS dm-kind (adds
    // the sender to allow_users), never group-kind.

    switch (working.dm_policy) {
      case 'disabled':
        return finish({ action: 'drop', reason: 'dm_disabled' });
      case 'all':
        return finish({ action: 'deliver' });
      case 'allowlist':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        return finish({
          action: 'drop',
          reason: 'group_user_not_on_allowlist',
          context: { sender_id: input.sender_id, chat_id: input.chat_id },
        });
      case 'pairing':
        if (working.allow_users.includes(input.sender_id)) {
          return finish({ action: 'deliver' });
        }
        // Rule 3: in-group pairing needs a mention (same as follow-user
        // gate). This triggers a dm-kind pair (adds sender to allow_users)
        // rather than any group-kind pair.
        if (!input.bot_mentioned) {
          return finish({
            action: 'drop',
            reason: 'group_pairing_stranger_not_mentioned',
            context: { sender_id: input.sender_id, chat_id: input.chat_id },
          });
        }
        return dmPairPath({ state: working, input, now, logs });
      default:
        return finish({ action: 'drop', reason: 'internal' });
    }
  }

  // Unsupported
  return finish({ action: 'drop', reason: 'unsupported_chat_type' });
}

// IO + UI helpers moved to feishu-gate-io.ts. Re-exported to preserve the
// public surface so callers (feishu-channel.ts, tests) need no change.
export {
  loadDispatcherAccess,
  readDispatcherAccess,
  saveDispatcherAccess,
} from './feishu-gate-io.js';
